/**************************************************************************/
/*  godot_physx_particle_fluid_3d.h                                       */
/**************************************************************************/
/*                         This file is part of:                          */
/*                             GODOT ENGINE                               */
/*                        https://godotengine.org                         */
/**************************************************************************/
/* Copyright (c) 2014-present Godot Engine contributors (see AUTHORS.md). */
/* Copyright (c) 2007-2014 Juan Linietsky, Ariel Manzur.                  */
/*                                                                        */
/* Permission is hereby granted, free of charge, to any person obtaining  */
/* a copy of this software and associated documentation files (the        */
/* "Software"), to deal in the Software without restriction, including    */
/* without limitation the rights to use, copy, modify, merge, publish,    */
/* distribute, sublicense, and/or sell copies of the Software, and to     */
/* permit persons to whom the Software is furnished to do so, subject to  */
/* the following conditions:                                              */
/*                                                                        */
/* The above copyright notice and this permission notice shall be         */
/* included in all copies or substantial portions of the Software.        */
/*                                                                        */
/* THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND,        */
/* EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF     */
/* MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. */
/* IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY   */
/* CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT,   */
/* TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE      */
/* SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.                 */
/**************************************************************************/

#pragma once

#include "core/math/aabb.h"
#include "core/math/vector3.h"
#include "core/math/vector4.h"
#include "core/templates/local_vector.h"
#include "core/templates/rid.h"
#include "core/templates/vector.h"

namespace physx {
class PxPBDParticleSystem;
class PxPBDMaterial;
class PxParticleAndDiffuseBuffer;
} //namespace physx

class GodotPhysXSpace3D;

// A GPU PBD fluid (PhysX 5 PxPBDParticleSystem). GPU-only; on a CPU build or
// without a CUDA device it stays inert. Owned in a space; positions are read
// back from the GPU after each step for the node to render.
class GodotPhysXParticleFluid3D {
public:
	enum Param {
		PARAM_VISCOSITY,
		PARAM_SURFACE_TENSION,
		PARAM_COHESION,
		PARAM_ADHESION,
		PARAM_VORTICITY,
		PARAM_GRAVITY_SCALE,
		PARAM_PARTICLE_SIZE,
		PARAM_MAX,
	};

private:
	RID self;
	GodotPhysXSpace3D *space = nullptr;

	physx::PxPBDParticleSystem *px_system = nullptr;
	physx::PxPBDMaterial *px_material = nullptr;
	physx::PxParticleAndDiffuseBuffer *px_buffer = nullptr;
	uint32_t fluid_phase = 0;

	uint32_t capacity = 8192; // particle buffer size
	uint32_t active_count = 0;
	uint32_t write_head = 0; // next slot to (over)write; ring-buffers when full

	// Diffuse (foam/spray/bubble) particles generated by the solver.
	bool foam_enabled = false;
	uint32_t foam_capacity = 16384;
	real_t foam_lifetime = 1.5;
	real_t foam_threshold = 300.0; // solver potential above which foam spawns
	real_t foam_buoyancy = 0.9;
	bool dirty_foam = true;
	uint32_t foam_count = 0;
	LocalVector<Vector4> foam_scratch; // pos.xyz + remaining lifetime.w
	LocalVector<Vector3> foam_positions;

	real_t viscosity = 0.01;
	real_t surface_tension = 0.006;
	real_t cohesion = 0.02;
	real_t adhesion = 0.0;
	real_t vorticity = 8.0;
	real_t gravity_scale = 1.0;
	real_t particle_size = 0.1; // spacing between particles at rest, in meters

	bool dirty_material = true;

	LocalVector<Vector4> read_scratch; // pos.xyz + inv-mass.w, one per active particle
	LocalVector<Vector3> read_positions;

	void _destroy();
	void _ensure_system();
	void _ensure_buffer();
	void _apply_material();
	void _apply_foam_params();
	void _write_particles(uint32_t p_at, const Vector<Vector3> &p_positions, const Vector3 &p_velocity);

public:
	void set_self(const RID &p_self) { self = p_self; }
	RID get_self() const { return self; }

	void set_space(GodotPhysXSpace3D *p_space);
	GodotPhysXSpace3D *get_space() const { return space; }

	void set_param(Param p_param, real_t p_value);
	real_t get_param(Param p_param) const;
	void set_capacity(uint32_t p_capacity);
	uint32_t get_capacity() const { return capacity; }

	// Diffuse particles. Enabling/resizing rebuilds the buffer; the rest push live.
	void set_foam_enabled(bool p_enabled);
	bool is_foam_enabled() const { return foam_enabled; }
	void set_foam_capacity(uint32_t p_capacity);
	uint32_t get_foam_capacity() const { return foam_capacity; }
	void set_foam_lifetime(real_t p_v);
	void set_foam_threshold(real_t p_v);
	void set_foam_buoyancy(real_t p_v);
	real_t get_foam_lifetime() const { return foam_lifetime; }
	real_t get_foam_threshold() const { return foam_threshold; }
	real_t get_foam_buoyancy() const { return foam_buoyancy; }
	const LocalVector<Vector3> &get_foam_positions() const { return foam_positions; }
	uint32_t get_foam_count() const { return foam_count; }

	// Replace the live particle set with a block at the given positions.
	void set_particles(const Vector<Vector3> &p_positions, const Vector3 &p_initial_velocity);
	// Add particles to the live set, recycling the oldest once the buffer is full.
	void emit(const Vector<Vector3> &p_positions, const Vector3 &p_velocity);
	void clear();

	// Called by the space after fetchResults(): copy positions GPU -> host.
	void read_back();
	const LocalVector<Vector3> &get_positions() const { return read_positions; }
	uint32_t get_particle_count() const { return active_count; }

	// Fraction (0..1) of the world-space box filled by fluid, from the fraction
	// of particles inside it scaled by particle volume. A cheap buoyancy probe.
	real_t get_submersion(const AABB &p_world_aabb) const;

	bool is_ready() const { return px_system != nullptr; }

	GodotPhysXParticleFluid3D() {}
	~GodotPhysXParticleFluid3D();
};
